### ISSUE TITLE
在访问路径页面解绑LUN时报错

### ISSUE THREAD

**Issue by 15611738763** [wuxingyi/iscsiproduct#12]
### target解绑已经映射的LUN
(1)提示：
`Target LUN mapping failed on ceph101. Unhandled exception: 'groups'`
(2)解绑LUN的接口：
`/api/v2/targetlun`
(3)报错内容及位置：#1078
```
   1078         for group_name, group in target_config['groups'].items():
   1079             if disk in group['disks']:
   1080                 return jsonify(message="Disk {} belongs to group "
   1081                                        "{}".format(disk, group_name)), 400
```

**Comment by wuxingyi** [comment]
fixed in commit: https://github.com/wuxingyi/iscsiproduct/commit/28cf2b08bcdc8295c1018acc0e42ebef49a22064
