### ISSUE TITLE
在访问路径页面解绑usergroup时报错

### ISSUE THREAD

**Issue by 15611738763** [wuxingyi/iscsiproduct#13]
### target解绑客户端组
（1）第一遍解绑时提示：
`Unhandled exception: list.remove(x): x not in list`
（2）报错日志：
`
-  File "/usr/lib/python2.7/site-packages/ceph_iscsi-3.0-py2.7.egg/EGG-INFO/scripts/rbd-target-api", line 113, in decorated
-   File "/usr/lib/python2.7/site-packages/ceph_iscsi-3.0-py2.7.egg/EGG-INFO/scripts/rbd-target-api", line 2985, in bindtarget
- ValueError: list.remove(x): x not in list

 `
（3）页面短暂消失已经解绑的客户端组：
![unbound_group1](https://user-images.githubusercontent.com/48903958/72528335-c1c69e00-38a5-11ea-8575-9491a9e1b88c.png)
（4）再次刷新后target_config['usergroups']中依然存在groupname；
![unbound_group2](https://user-images.githubusercontent.com/48903958/72528050-1f0e1f80-38a5-11ea-9bae-757c9a27c752.png)
![UNbound_group](https://user-images.githubusercontent.com/48903958/72527959-e66e4600-38a4-11ea-9ff9-f917caed8017.png)

**Comment by wuxingyi** [comment]
fixed by  commit https://github.com/wuxingyi/iscsiproduct/commit/39a85cbb3a005f7175b619dfe8ddab9887583fdc
